import QRCode from 'qrcode';
import jsQR from 'jsqr';

const VERSION='0.20.8', MAGIC='OL205', PAYLOAD=1000, TX_QPS=8;
const MODES=[{id:'M12',label:'12 Hz',hz:12,dur:90},{id:'M18',label:'18 Hz',hz:18,dur:90},{id:'M24',label:'24 Hz',hz:24,dur:90},{id:'MAX',label:'Camera-driven',hz:0,dur:90},{id:'END',label:'Camera-driven Endurance',hz:0,dur:300}];
const TOTAL=70+MODES.reduce((a,m)=>a+m.dur+2,0)+5;
const app=document.getElementById('app');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
const median=a=>{if(!a.length)return 0;let b=[...a].sort((x,y)=>x-y),n=b.length;return n%2?b[(n-1)/2]:(b[n/2-1]+b[n/2])/2};
const cv=a=>{if(a.length<2)return 0;const m=mean(a),s=Math.sqrt(a.reduce((z,v)=>z+(v-m)**2,0)/(a.length-1));return m?s/m*100:0};
const fmt=b=>b>=1000?`${(b/1000).toFixed(2)} KB/s`:`${Math.round(b)} B/s`;
const sid=()=>Math.random().toString(36).slice(2,8).toUpperCase()+Date.now().toString(36).slice(-4).toUpperCase();
let crcTable=null;function crc32(s){if(!crcTable){crcTable=[];for(let i=0;i<256;i++){let c=i;for(let k=0;k<8;k++)c=(c&1)?0xEDB88320^(c>>>1):c>>>1;crcTable[i]=c>>>0}}let c=0xffffffff;for(let i=0;i<s.length;i++)c=(c>>>8)^crcTable[(c^s.charCodeAt(i))&255];return((c^0xffffffff)>>>0).toString(16).padStart(8,'0')}
function payload(seq){const p=`${seq.toString(36).padStart(6,'0')}:`;let s='';while(s.length<PAYLOAD)s+=`A7F3${p}Q9K2M5N8`;return s.slice(0,PAYLOAD)}
function pktD(session,phase,seq,prev=''){const body=`${MAGIC}|D|${session}|${phase}|${seq}|${prev}|${payload(seq)}`;return `${body}|${crc32(body)}`}
const pktH=s=>`${MAGIC}|H|${s}|${VERSION}|${PAYLOAD}|${TX_QPS}`;
const pktS=(s,p,c,d)=>`${MAGIC}|S|${s}|${p}|${c}|${d.toFixed(1)}|${(c/(d/1000)).toFixed(3)}`;
const pktE=(s,p)=>`${MAGIC}|E|${s}|${p}`;
function parse(text){if(!text||!text.startsWith(MAGIC+'|'))return null;const a=text.split('|'),type=a[1],session=a[2];if(type==='D'){if(a.length<8)return null;const phase=a[3],seq=+a[4],prev=a[5],hash=a[a.length-1],data=a.slice(6,-1).join('|'),body=`${MAGIC}|D|${session}|${phase}|${seq}|${prev}|${data}`;if(crc32(body)!==hash||data.length!==PAYLOAD)return null;return{type,session,phase,seq,prev}}if(type==='S')return{type,session,phase:a[3],count:+a[4],durMs:+a[5],qps:+a[6]};if(type==='H')return{type,session};if(type==='E')return{type,session,last:a[3]};return null}
function shell(role){return `<div class="page"><div class="top"><div><b>Optical Link Bench V${VERSION}</b><div class="muted">1000B × 8 QR/s · Decoder Sampling Benchmark</div></div><button class="btn" id="switch">${role==='tx'?'接收端':'發射端'}</button></div><div id="body" class="grid ${role==='rx'?'rx':''}"></div></div>`}
function route(){const role=location.hash.includes('rx')?'rx':'tx';app.innerHTML=shell(role);document.getElementById('switch').onclick=()=>{location.hash=role==='tx'?'rx':'tx'};role==='tx'?renderTx():renderRx()}
window.addEventListener('hashchange',route);
function libsReady(){return true}
function showLibError(){if(document.getElementById('liberr'))return;const d=document.createElement('div');d.id='liberr';d.className='liberr';d.innerHTML=`<div><h2>必要元件初始化失敗</h2><p>QRCode / jsQR 已由本站 bundle 提供，但初始化未成功。</p><p class="muted">請重新整理；若問題持續，請查看瀏覽器 Console。</p><button class="btn blue" onclick="location.reload()">重新整理</button></div>`;document.body.appendChild(d)}
async function drawQR(canvas,text,width=900){if(!libsReady())throw new Error('QR libraries unavailable');await QRCode.toCanvas(canvas,text,{errorCorrectionLevel:'L',margin:4,width,color:{dark:'#000000',light:'#ffffff'}})}
function renderTx(){const b=document.getElementById('body');b.innerHTML=`<div class="card side"><div class="hero"><small>目前階段</small><b id="phase">等待</b></div><div class="bar"><i id="prog"></i></div><div class="stats"><div class="stat"><small>Payload</small><b>1000 B</b></div><div class="stat"><small>TX rate</small><b>8 QR/s</b></div><div class="stat"><small>Elapsed</small><b id="elapsed">0:00</b></div><div class="stat"><small>ETA</small><b id="eta">~12m</b></div></div><div class="modegrid">${MODES.map(m=>`<div class="modepill" data-m="${m.id}">${m.label}</div>`).join('')}</div><button class="btn blue" id="start">開始 V0.20 完整測試</button><button class="btn red" id="stop">停止</button><div class="note">10s START → 60s warm-up → 12/18/24 Hz 各 90s → Camera-driven 90s → 300s endurance。整頁固定在一個 viewport 內。</div></div><div class="card stage"><canvas id="qr" width="900" height="900"></canvas><div class="badge" id="badge">READY</div></div>`;
let stop=false,running=false;document.getElementById('stop').onclick=()=>stop=true;document.getElementById('start').onclick=async()=>{if(running)return;if(!libsReady()){showLibError();return}running=true;stop=false;const s=sid(),canvas=document.getElementById('qr'),phase=document.getElementById('phase'),badge=document.getElementById('badge'),prog=document.getElementById('prog'),t0=performance.now();let seq=0,prev='';const timer=setInterval(()=>{let e=(performance.now()-t0)/1000;document.getElementById('elapsed').textContent=`${Math.floor(e/60)}:${String(Math.floor(e%60)).padStart(2,'0')}`;document.getElementById('eta').textContent=`~${Math.max(0,Math.ceil(TOTAL-e))}s`;prog.style.width=`${clamp(e/TOTAL*100,0,100)}%`},250);try{phase.textContent='START · 10s';badge.textContent=`START · ${s}`;await drawQR(canvas,pktH(s),760);await sleep(10000);if(stop)throw new Error('stopped');phase.textContent='Warm-up · 60s';await runPhase('WARM',60);for(const m of MODES){if(stop)break;document.querySelectorAll('.modepill').forEach(x=>x.classList.toggle('on',x.dataset.m===m.id));phase.textContent=`${m.label} · ${m.dur}s`;await runPhase(m.id,m.dur)}if(!stop){phase.textContent='完成';for(let i=0;i<30;i++){await drawQR(canvas,pktE(s,prev),620);await sleep(150)}}}catch(e){phase.textContent=stop?'已停止':'錯誤';badge.textContent=e.message}clearInterval(timer);running=false;async function runPhase(id,dur){let count=0,start=performance.now(),end=start+dur*1000,next=start,period=1000/TX_QPS;while(performance.now()<end&&!stop){const now=performance.now();if(now<next)await sleep(next-now);if(performance.now()>=end)break;await drawQR(canvas,pktD(s,id,seq++,prev),900);count++;badge.textContent=`${id} · #${count}`;next=start+count*period}const elapsed=performance.now()-start;prev=`${id},${count},${elapsed.toFixed(0)}`;for(let i=0;i<8&&!stop;i++){await drawQR(canvas,pktS(s,id,count,elapsed),620);badge.textContent=`SUMMARY · ${id}`;await sleep(250)}}}}
let receiver=null;function renderRx(){const b=document.getElementById('body');b.innerHTML=`<div class="card cam"><div class="view"><video id="video" playsinline muted></video><div class="roi" id="roi"></div></div><div id="lock" class="muted">相機尚未啟動</div></div><div class="card side"><div class="hero"><small>LINK</small><b id="state">WAITING</b></div><div class="stats"><div class="stat"><small>Mode</small><b id="mode">—</b></div><div class="stat"><small>Attempts/s</small><b id="attemptRate">—</b></div><div class="stat"><small>Unique QR/s</small><b id="uniqueRate">—</b></div><div class="stat"><small>Camera FPS</small><b id="camFps">—</b></div><div class="stat"><small>ROI ms</small><b id="roiMs">—</b></div><div class="stat"><small>Full ms</small><b id="fullMs">—</b></div><div class="stat"><small>Duplicates/s</small><b id="dupRate">—</b></div><div class="stat"><small>Efficiency</small><b id="eff">—</b></div></div><button class="btn blue" id="camera">啟動並等待 V0.20</button><button class="btn red" id="stopcam">停止相機</button><div class="bar"><i id="rprog"></i></div><div class="note">固定 1000B × 8/s。只比較 decoder sampling；相機畫面與控制區保持同屏。</div></div>`;document.getElementById('camera').onclick=startCamera;document.getElementById('stopcam').onclick=()=>stopCamera()}
async function startCamera(){if(receiver)return;if(!libsReady()){showLibError();return}const v=document.getElementById('video'),state=document.getElementById('state'),lock=document.getElementById('lock');try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30,max:60}},audio:false});v.srcObject=stream;await v.play();receiver=makeReceiver(v,stream);state.textContent='CAMERA READY';lock.textContent=`Camera ${v.videoWidth}×${v.videoHeight}`;lock.classList.add('locked');receiver.start()}catch(e){state.textContent='CAMERA ERROR';lock.textContent=`${e.name}: ${e.message}`}}
function stopCamera(){if(receiver){receiver.stop();receiver=null}}
function makeReceiver(video,stream){const full=document.createElement('canvas'),fc=full.getContext('2d',{willReadFrequently:true}),crop=document.createElement('canvas'),cc=crop.getContext('2d',{willReadFrequently:true});let alive=true,session=null,phase='WARM',roi=null,lastAttempt=0,presented=0,attempts=0,unique=0,dups=0,lastStats=performance.now(),snap={a:0,u:0,d:0,p:0};const trials=new Map(),summaries=new Map(),roiTimes=[],fullTimes=[];
const getTrial=id=>{if(!trials.has(id))trials.set(id,{seen:new Set(),first:0,last:0,attempts:0,dups:0,p0:presented,p1:presented,roi:[],full:[],wins:new Map()});return trials.get(id)};
const targetHz=()=>phase==='M12'?12:phase==='M18'?18:phase==='M24'?24:0;
function allowed(now){let hz=targetHz();return hz?now-lastAttempt>=1000/hz-2:true}
function updateROI(loc,ox,oy,w,h){let xs=[loc.topLeftCorner.x,loc.topRightCorner.x,loc.bottomLeftCorner.x,loc.bottomRightCorner.x].map(x=>x+ox),ys=[loc.topLeftCorner.y,loc.topRightCorner.y,loc.bottomLeftCorner.y,loc.bottomRightCorner.y].map(y=>y+oy);let x0=Math.min(...xs),x1=Math.max(...xs),y0=Math.min(...ys),y1=Math.max(...ys),pad=Math.max(x1-x0,y1-y0)*.18;roi={x:clamp(x0-pad,0,w),y:clamp(y0-pad,0,h),w:clamp(x1-x0+2*pad,20,w),h:clamp(y1-y0+2*pad,20,h)};drawROI()}
function drawROI(){let el=document.getElementById('roi');if(!el)return;if(!roi){el.style.display='none';return}let r=video.getBoundingClientRect(),sx=r.width/video.videoWidth,sy=r.height/video.videoHeight;el.style.display='block';el.style.left=`${roi.x*sx}px`;el.style.top=`${roi.y*sy}px`;el.style.width=`${roi.w*sx}px`;el.style.height=`${roi.h*sy}px`}
function scan(){let now=performance.now();if(!allowed(now))return;lastAttempt=now;attempts++;let tr=getTrial(phase);tr.attempts++;let w=video.videoWidth,h=video.videoHeight;if(!w||!h)return;full.width=w;full.height=h;fc.drawImage(video,0,0,w,h);let code=null;if(roi){let x=Math.floor(clamp(roi.x,0,w-2)),y=Math.floor(clamp(roi.y,0,h-2)),rw=Math.floor(clamp(roi.w,2,w-x)),rh=Math.floor(clamp(roi.h,2,h-y));crop.width=rw;crop.height=rh;cc.drawImage(full,x,y,rw,rh,0,0,rw,rh);let im=cc.getImageData(0,0,rw,rh),t=performance.now();code=jsQR(im.data,rw,rh,{inversionAttempts:'dontInvert'});let dt=performance.now()-t;roiTimes.push(dt);tr.roi.push(dt);if(code&&code.location)updateROI(code.location,x,y,w,h)}if(!code){let im=fc.getImageData(0,0,w,h),t=performance.now();code=jsQR(im.data,w,h,{inversionAttempts:'dontInvert'});let dt=performance.now()-t;fullTimes.push(dt);tr.full.push(dt);if(code&&code.location)updateROI(code.location,0,0,w,h)}if(code)handle(code.data,performance.now())}
function handle(text,now){const p=parse(text);if(!p||session&&p.session!==session)return;if(!session){session=p.session;document.getElementById('state').textContent='LINK LOCKED';document.getElementById('lock').textContent=`Session ${session} · via ${p.type}`;document.getElementById('lock').classList.add('locked')}if(p.type==='D'){phase=p.phase;const tr=getTrial(phase);if(!tr.first)tr.first=now;tr.last=now;tr.p1=presented;if(tr.seen.has(p.seq)){dups++;tr.dups++}else{tr.seen.add(p.seq);unique++;let wi=Math.floor((now-tr.first)/10000);tr.wins.set(wi,(tr.wins.get(wi)||0)+1)}document.getElementById('mode').textContent=label(phase)}else if(p.type==='S'){summaries.set(p.phase,p);updateEff()}else if(p.type==='E'){setTimeout(showReport,400)}}
function label(x){return({WARM:'Warm-up',M12:'12 Hz',M18:'18 Hz',M24:'24 Hz',MAX:'Camera-driven',END:'Endurance'})[x]||x}
function updateEff(){let s=summaries.get(phase),t=trials.get(phase);document.getElementById('eff').textContent=s&&t?`${(t.seen.size/s.count*100).toFixed(1)}%`:'—'}
function onFrame(){if(!alive)return;presented++;scan();if(video.requestVideoFrameCallback)video.requestVideoFrameCallback(onFrame);else requestAnimationFrame(onFrame)}
function stats(){if(!alive)return;let now=performance.now(),dt=(now-lastStats)/1000;if(dt>=1){document.getElementById('attemptRate').textContent=((attempts-snap.a)/dt).toFixed(1);document.getElementById('uniqueRate').textContent=((unique-snap.u)/dt).toFixed(1);document.getElementById('dupRate').textContent=((dups-snap.d)/dt).toFixed(1);document.getElementById('camFps').textContent=((presented-snap.p)/dt).toFixed(1);document.getElementById('roiMs').textContent=roiTimes.length?median(roiTimes.slice(-40)).toFixed(1):'—';document.getElementById('fullMs').textContent=fullTimes.length?median(fullTimes.slice(-20)).toFixed(1):'—';snap={a:attempts,u:unique,d:dups,p:presented};lastStats=now;updateEff()}requestAnimationFrame(stats)}
function rows(){return MODES.map(m=>{let t=trials.get(m.id),s=summaries.get(m.id);if(!t)return null;let dur=s?s.durMs/1000:(t.last-t.first)/1000,tx=s?s.count:Math.round(dur*TX_QPS),u=t.seen.size,good=dur?u*PAYLOAD/dur:0,eff=tx?u/tx*100:0,ar=dur?t.attempts/dur:0,dr=dur?t.dups/dur:0,cf=dur?(t.p1-t.p0)/dur:0,wvals=[...t.wins.values()].map(v=>v*PAYLOAD/10);return{m,dur,tx,u,good,eff,ar,dr,cf,wcv:cv(wvals),r:median(t.roi),f:median(t.full)}}).filter(Boolean)}
function showReport(){if(document.getElementById('report'))return;let rs=rows(),best=[...rs].filter(r=>r.m.id!=='END').sort((a,b)=>b.good-a.good)[0],be=[...rs].filter(r=>r.m.id!=='END').sort((a,b)=>b.eff-a.eff)[0],end=rs.find(r=>r.m.id==='END'),ok=end&&end.eff>=90&&end.wcv<=20&&end.good>=7200;let d=document.createElement('div');d.id='report';d.className='report on';d.innerHTML=`<div class="top"><div><b>V${VERSION} Decoder Sampling 報告</b><div class="muted">固定 1000B × 8 QR/s</div></div><button class="btn" id="closeRep">關閉</button></div><div class="lead"><div><small>Best 90s Goodput</small><b>${best?fmt(best.good):'—'}</b><div class="muted">${best?best.m.label:'—'}</div></div><div><small>Best 90s Efficiency</small><b>${be?be.eff.toFixed(1)+'%':'—'}</b><div class="muted">${be?be.m.label:'—'}</div></div><div><small>300s Endurance</small><b>${end?fmt(end.good):'—'}</b><div class="muted">${end?`Eff ${end.eff.toFixed(1)}% · CV ${end.wcv.toFixed(1)}%`:'—'}</div></div><div><small>Validated</small><b class="${ok?'ok':'warn'}">${ok?'通過':'未通過'}</b></div></div><div class="tbl"><table><thead><tr><th>Mode</th><th>Goodput</th><th>Eff</th><th>Attempts/s</th><th>Unique/s</th><th>Dup/s</th><th>Camera FPS</th><th>10s CV</th><th>ROI ms</th><th>Full ms</th></tr></thead><tbody>${rs.map(r=>`<tr><td>${r.m.label}</td><td>${fmt(r.good)}</td><td>${r.eff.toFixed(1)}%</td><td>${r.ar.toFixed(1)}</td><td>${(r.u/r.dur).toFixed(2)}</td><td>${r.dr.toFixed(1)}</td><td>${r.cf.toFixed(1)}</td><td>${r.wcv.toFixed(1)}%</td><td>${r.r?r.r.toFixed(1):'—'}</td><td>${r.f?r.f.toFixed(1):'—'}</td></tr>`).join('')}</tbody></table></div>`;document.body.appendChild(d);document.getElementById('closeRep').onclick=()=>d.remove()}
return{start(){alive=true;if(video.requestVideoFrameCallback)video.requestVideoFrameCallback(onFrame);else requestAnimationFrame(onFrame);requestAnimationFrame(stats)},stop(){alive=false;stream.getTracks().forEach(t=>t.stop())}}
}
route();
